# 驱动 mysql pgsql sqlite
driver: pgsql
# 数据库名
database: gfa
# postgresql模式名称
schema: public
# 用户名
username: postgres
# 密码
password: postgres
# 主机地址
host: 127.0.0.1
# 端口
port: 5432
# 连接字符串查询参数
query: parseTime=True&loc=Local&timeout=10000ms
# 是否打印日志
log-mode: true
# 编码方式
charset: utf8mb4
# postgresql 参数
time-zone: Asia/Shanghai
# postgresql 参数
ssl-mode: disable